"""Structured report generation for the actions MCP server.

Produces Markdown-formatted reports from structured signal data,
suitable for GitHub issues, documentation, or audit logs.
"""

from __future__ import annotations

import hashlib
import json
import logging
from datetime import datetime, timezone
from typing import Any

logger = logging.getLogger(__name__)


def _now_iso() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def _report_id(content: str) -> str:
    """Generate a short deterministic report ID from content hash."""
    return "RPT-" + hashlib.sha256(content.encode()).hexdigest()[:12].upper()


# ---------------------------------------------------------------------------
# Report builders
# ---------------------------------------------------------------------------


def build_security_report(
    *,
    repository: str,
    overall_risk: str,
    dependency_summary: dict[str, Any],
    secret_summary: dict[str, Any],
    critical_findings: list[dict[str, Any]],
    recommendations: list[str],
) -> dict[str, Any]:
    """Build a comprehensive security audit report.

    Returns a dict with ``report_id``, ``markdown``, and structured
    metadata.
    """
    now = _now_iso()
    md_lines = [
        "# 🛡️ ARCHON Security Audit Report",
        "",
        f"**Repository:** `{repository}`",
        f"**Generated:** {now}",
        f"**Overall Risk Level:** **{overall_risk.upper()}**",
        "",
        "---",
        "",
        "## Executive Summary",
        "",
    ]

    dep_count = dependency_summary.get("vulnerability_count", 0)
    secret_count = secret_summary.get("finding_count", 0)

    if overall_risk in ("critical", "high"):
        md_lines.append(
            f"⚠️ **This repository has significant security concerns.** "
            f"{dep_count} dependency vulnerability/ies and {secret_count} "
            f"potential secret leak(s) were detected."
        )
    elif overall_risk == "medium":
        md_lines.append(
            f"This repository has moderate security concerns with "
            f"{dep_count} dependency vulnerability/ies and {secret_count} "
            f"potential secret finding(s)."
        )
    else:
        md_lines.append(
            "No critical security issues were detected. Continue regular monitoring."
        )

    md_lines.append("")

    # -- dependency section --------------------------------------------------
    md_lines.extend([
        "## Dependency Vulnerabilities",
        "",
        f"- **Risk Level:** {dependency_summary.get('risk_level', 'none')}",
        f"- **Vulnerabilities Found:** {dep_count}",
    ])

    dep_dist = dependency_summary.get("severity_distribution", {})
    if any(dep_dist.values()):
        md_lines.append(f"- **Severity Breakdown:** "
                        f"Critical: {dep_dist.get('CRITICAL', 0)}, "
                        f"High: {dep_dist.get('HIGH', 0)}, "
                        f"Medium: {dep_dist.get('MEDIUM', 0)}, "
                        f"Low: {dep_dist.get('LOW', 0)}")
    md_lines.append("")

    # -- secret section ------------------------------------------------------
    md_lines.extend([
        "## Secret / Credential Findings",
        "",
        f"- **Risk Level:** {secret_summary.get('risk_level', 'none')}",
        f"- **Findings:** {secret_count}",
    ])

    sec_dist = secret_summary.get("severity_distribution", {})
    if any(sec_dist.values()):
        md_lines.append(f"- **Severity Breakdown:** "
                        f"Critical: {sec_dist.get('critical', 0)}, "
                        f"High: {sec_dist.get('high', 0)}, "
                        f"Medium: {sec_dist.get('medium', 0)}")
    md_lines.append("")

    # -- critical findings table ---------------------------------------------
    if critical_findings:
        md_lines.extend([
            "## Critical Findings",
            "",
            "| # | Type | Severity | Detail |",
            "|---|------|----------|--------|",
        ])
        for i, f in enumerate(critical_findings[:15], 1):
            ftype = f.get("cve_id") or f.get("secret_type") or "Unknown"
            sev = f.get("severity", "unknown")
            detail = (f.get("description") or f.get("preview") or "—")[:60]
            md_lines.append(f"| {i} | `{ftype}` | {sev} | {detail} |")
        md_lines.append("")

    # -- recommendations -----------------------------------------------------
    if recommendations:
        md_lines.extend([
            "## Recommendations",
            "",
        ])
        for i, rec in enumerate(recommendations, 1):
            md_lines.append(f"{i}. {rec}")
        md_lines.append("")

    md_lines.extend([
        "---",
        "",
        "*Generated by ARCHON — MCP-based operational control system on Archestra.*",
    ])

    markdown = "\n".join(md_lines)
    report_id = _report_id(markdown)

    return {
        "report_type": "security_audit",
        "report_id": report_id,
        "repository": repository,
        "overall_risk_level": overall_risk,
        "generated_at": now,
        "dependency_summary": dependency_summary,
        "secret_summary": secret_summary,
        "critical_finding_count": len(critical_findings),
        "recommendation_count": len(recommendations),
        "markdown": markdown,
    }


def build_operational_report(
    *,
    repository: str,
    health_score: int,
    grade: str,
    commit_risk: str,
    pr_risk: str,
    security_risk: str,
    health_details: dict[str, Any],
    commit_summary: dict[str, Any],
    pr_summary: dict[str, Any],
    security_summary: dict[str, Any],
    action_items: list[str],
) -> dict[str, Any]:
    """Build a full operational status report combining all signals.

    This is the "big picture" report that the orchestrator generates
    after correlating all signals.
    """
    now = _now_iso()

    # Determine overall status
    risks = [commit_risk, pr_risk, security_risk]
    risk_order = {"none": 0, "low": 1, "medium": 2, "high": 3, "critical": 4}
    overall_risk = max(risks, key=lambda r: risk_order.get(r, 0))

    md_lines = [
        "# 📊 ARCHON Operational Status Report",
        "",
        f"**Repository:** `{repository}`",
        f"**Generated:** {now}",
        f"**Health Score:** {health_score}/100 (Grade: {grade})",
        f"**Overall Risk:** **{overall_risk.upper()}**",
        "",
        "---",
        "",
        "## Signal Summary",
        "",
        "| Signal | Risk Level | Key Metric |",
        "|--------|-----------|------------|",
        f"| Repository Health | {grade} | Score: {health_score}/100 |",
        f"| Commit Activity | {commit_risk} | {commit_summary.get('commits_analyzed', 0)} commits analyzed |",
        f"| Pull Requests | {pr_risk} | {pr_summary.get('open_prs_analyzed', 0)} open PRs |",
        f"| Security | {security_risk} | {security_summary.get('vulnerability_count', 0)} vulnerabilities |",
        "",
    ]

    # -- dimensions ----------------------------------------------------------
    dimensions = health_details.get("dimensions", {})
    if dimensions:
        md_lines.extend([
            "## Health Dimensions",
            "",
            "| Dimension | Score | Max |",
            "|-----------|-------|-----|",
        ])
        for dim_name, dim_data in dimensions.items():
            md_lines.append(
                f"| {dim_name.replace('_', ' ').title()} | "
                f"{dim_data.get('score', 0)} | {dim_data.get('max', 0)} |"
            )
        md_lines.append("")

    # -- action items --------------------------------------------------------
    if action_items:
        md_lines.extend([
            "## Prioritized Action Items",
            "",
        ])
        for i, item in enumerate(action_items, 1):
            md_lines.append(f"{i}. {item}")
        md_lines.append("")

    md_lines.extend([
        "---",
        "",
        "*Generated by ARCHON — MCP-based operational control system on Archestra.*",
    ])

    markdown = "\n".join(md_lines)
    report_id = _report_id(markdown)

    return {
        "report_type": "operational_status",
        "report_id": report_id,
        "repository": repository,
        "overall_risk_level": overall_risk,
        "health_score": health_score,
        "grade": grade,
        "generated_at": now,
        "signal_risks": {
            "commit_activity": commit_risk,
            "pull_requests": pr_risk,
            "security": security_risk,
        },
        "action_item_count": len(action_items),
        "markdown": markdown,
    }
